sudo: false

language: python

python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - python setup.py install
  - pip install -r test-requirements.txt

script: nosetests --with-coverage --cover-package=marten

after_success:
  coveralls
